### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by col42dev** [col42dev/dataminerbackfiller#1]
$ screen -r  25889.pts-0.ip-172-31-1-196
editing...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/339pe.json
editing...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/22cm6.json
editing...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/2hewe.json
editing...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/28kay.json
editing...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/457gd.json
fstatEdited
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/51viy.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/1a9rm.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/1184a.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/4rrxs.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/4xb60.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/339pe.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/22cm6.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/2hewe.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/28kay.json
fstating...//ST_Prototypes/ML/SliceOfMine/Assets/Resources/RulesData/457gd.json
getJSON
writeUpdates
revertUnchangedUpdates
revertUnchangedUpdates completed
submitUpdates
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................undefined:1
<h1>This website is under heavy load</h1><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/ec2user/dataminer/backfiller/backfiller/backfiller.js:192:27)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickDomainCallback (node.js:405:17)

**Comment by col42dev** [comment]
JSON.Parse exception handled added.
https://github.com/col42dev/dataminerbackfiller/commit/15024b58da4ac722e0a4946d66df8ce8cd904453
